export const randomQuotes: string[] = [
  "You don't need to do everything today, just something that moves you forward.",
  "Consistency beats intensity when intensity isn't sustainable.",
  "Looking after your body isn't a chore, it's maintenance for everything else you want to do.",
  "Your mood often follows your actions, not the other way around.",
  "Small habits compound quietly until they become obvious.",
  "Rest is not a reward, it's part of the process.",
  "You're allowed to take progress seriously without taking yourself too seriously.",
  "Most people overestimate what they can do in a day and underestimate what they can do in a year.",
  "Your future self benefits from what you choose to repeat today.",
  "You don't have to feel motivated to act, just willing.",
  "Taking care of your mental health is productive, even if it doesn't look like it.",
  "A short walk still counts. A small win still counts. It all counts.",
  "The goal isn't perfection, it's direction.",
  "Being reliable to yourself builds more confidence than any external validation.",
  "You can't optimise a life you're too burnt out to live.",
  "Saying no to something is often saying yes to something more important.",
  "Momentum is built, not found.",
  "Your environment shapes your behaviour more than your intentions do.",
  "Progress that feels slow is still progress.",
  "You're not behind, you're just early in your own timeline.",
  "Investing in your health pays dividends you actually get to experience.",
  "It's okay if today's version of ‘your best' looks different from yesterday's.",
  "Most good habits feel insignificant while you're building them.",
  "Discipline is just remembering what you actually want.",
  "Your attention is a limited resource, spend it deliberately.",
  "You don't need a full plan, just a next step.",
  "Caring for your relationships is part of caring for yourself.",
  "Financial stability is built on boring, consistent decisions.",
  "You don't rise to your goals, you fall to your systems.",
  "A clear mind starts with small acts of order.",
  "Doing something imperfectly is often the fastest way to get better at it.",
  "Your habits are votes for the kind of life you want.",
  "It's fine to go slower if it means you keep going.",
  "The version of you that you respect is built through repetition, not intention.",
  "Energy management matters more than time management.",
  "You're allowed to change your approach without calling it failure.",
  "Social connection isn't optional, it's part of being well.",
  "Most setbacks are temporary unless you decide they aren't.",
  "You don't need to earn the right to take care of yourself.",
  "Long-term thinking makes short-term decisions easier.",
  "A little structure can create a lot of freedom.",
  "Showing up on low-motivation days is where most growth happens.",
  "You can be kind to yourself without letting yourself off the hook.",
  "Not every day needs to be productive to be worthwhile.",
  "The basics done well will take you further than complex plans done rarely.",
  "Your career is a long game, not a series of sprints.",
  "It's easier to stay consistent when you make things slightly easier for yourself.",
  "Improvement isn't linear, but effort still matters.",
  "You're building something, even when it doesn't feel like it."
];